# Multi stage production image.
FROM node:20-alpine AS builder

RUN apk add --no-cache openssl

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,id=npm-backend,target=/root/.npm npm install

COPY . .
RUN npm run prisma:generate
RUN npm run build

FROM node:20-alpine AS runtime

RUN apk add --no-cache openssl

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY scripts ./scripts

EXPOSE 3000

CMD ["sh", "-c", "node scripts/migrate.js && node dist/index.js"]
