# Multi stage production image.
FROM node:20-alpine AS builder

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,id=npm-email,target=/root/.npm npm install

COPY . .
RUN npm run build

FROM node:20-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3001

CMD ["node", "dist/index.js"]
